development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vacaybug
  pool: 5
  username: root
  password: mysql
  port: 3306
  collation: utf8_general_ci

test:
  adapter: postgresql
  encoding: utf8
  database: d446updv740hr9
  host: ec2-54-235-76-206.compute-1.amazonaws.com
  pool: 5
  username: umoxmjcyifzoas
  password: iTTPW_As9R70F7zSlbWrXRZx4A

production:
  adapter: postgresql
  encoding: utf8
  database: d446updv740hr9
  host: ec2-54-235-76-206.compute-1.amazonaws.com
  pool: 5
  username: umoxmjcyifzoas
  password: iTTPW_As9R70F7zSlbWrXRZx4A
  collation: utf8_general_ci
